version: '3.9'

services:
  web:
    build: .
    command: bash -c "poetry run src/manage.py makemigrations && poetry run src/manage.py migrate && poetry run src/manage.py loaddata src/fixtures/achievements.yaml && poetry run src/manage.py runserver 0.0.0.0:8002"
    container_name: habitual_life
    volumes:
      - .:/habitual_life
    ports:
      - "8002:8002"
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    command: bash -c "cd src && poetry run celery -A core worker --loglevel=INFO --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo"
    container_name: habitual_life_celery_worker
    volumes:
      - .:/habitual_life
    environment:
      CELERY_BROKER_URL: "redis://habitual_life_redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://habitual_life_redis:6379/0"
    depends_on:
      - redis
    healthcheck:
      test: celery inspect ping
      interval: 1m
      timeout: 10s
      retries: 10

  redis:
    image: "redis:latest"
    container_name: habitual_life_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1m
      timeout: 10s
      retries: 10

  db:
    container_name: postgresql_db
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 5s
      timeout: 30s
      retries: 6
