# Generated by Django 4.2.7 on 2023-12-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0002_rename_date_habit_created_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_category"
            ),
        ),
    ]
