# Generated by Django 4.2.7 on 2023-12-14 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0006_alter_category_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="unique_user_category",
        ),
    ]
