# Generated by Django 4.2.7 on 2023-12-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0007_remove_category_unique_user_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to="habits.category",
            ),
        ),
    ]
