# Generated by Django 4.2.7 on 2023-12-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0008_alter_habit_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="category",
            field=models.ForeignKey(
                choices=[
                    ("HEALTH", "Health"),
                    ("FINANCE", "Finance"),
                    ("WORK", "Work"),
                ],
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to="habits.category",
            ),
        ),
    ]
