# Generated by Django 5.0 on 2023-12-15 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0010_alter_habit_category_alter_habit_user"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("name", "user")},
        ),
    ]
