# Generated by Django 5.0 on 2023-12-20 16:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0011_alter_category_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#FF0000", image_field=None, max_length=25, samples=None
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default=None,
                max_length=8,
            ),
        ),
    ]
