# Generated by Django 5.0 on 2023-12-20 17:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0013_remove_habit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=colorfield.fields.ColorField(
                default="#d3d3d3", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
