# Generated by Django 5.0 on 2023-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0014_alter_category_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="created_date",
        ),
        migrations.AddField(
            model_name="habit",
            name="execution_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="failed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="skipped_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="habit",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default=None,
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="success_count",
            field=models.IntegerField(default=0),
        ),
    ]
