# Generated by Django 5.0 on 2023-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0016_alter_habit_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped"),
                ],
                default=None,
                max_length=7,
                null=True,
            ),
        ),
    ]
