# Generated by Django 5.0 on 2023-12-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0019_alter_habit_execution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="execution_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
