# Generated by Django 5.0 on 2023-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0020_alter_habit_execution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[("DAILY", "Daily"), ("INTERVAL", "Interval")],
                default=None,
                max_length=10,
            ),
        ),
    ]
