# Generated by Django 5.0 on 2023-12-30 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0021_alter_habit_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="interval_value",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("INTERVAL", "Interval"),
                    ("MONTHLY", "Monthly"),
                ],
                default=None,
                max_length=10,
            ),
        ),
    ]
