# Generated by Django 5.0 on 2024-01-04 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="image",
        ),
    ]
