# Generated by Django 5.0 on 2024-01-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0003_alter_achievement_user"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="user",
        ),
        migrations.AddField(
            model_name="achievement",
            name="user",
            field=models.ManyToManyField(to="users.profile"),
        ),
    ]
