# Generated by Django 5.0 on 2024-01-16 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("achievements", "0005_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
